### ISSUE TITLE
Blockstack Key Implementation

### ISSUE THREAD

**Issue by itamarreif** [universelabs/universe-core#5]
**Description**
After #4 is complete and as Blockstack key derivation will be implemented on the feather device, the mocked structs should be replaced with a real representation.

**Tasks**
- [x] Research how Blockstack keys are structured and what data needs to be held
- [ ] Implement in universe/wallet.go

**Useful Resources**
- https://github.com/blockstack/blockstack.js/blob/master/src/wallet.ts
- https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
- https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
- https://github.com/tyler-smith/go-bip39

**Comment by guylepage3** [comment]
Pushing this to [Sprint 7](https://github.com/orgs/universelabs/projects/8).

**Comment by faddat** [comment]
Closing; feather-related
